### ISSUE TITLE
Error when running `./bin/process.sh csvAccountExtractProcess`

### ISSUE THREAD

**Issue by syahmifauzi** [mhamzas/Scripted-Data-Loader-for-Mac-Unix#2]
Hi, Hamza, are you still maintaining this script? I need some help, I am running Ubuntu 20.04 LTS. I follow your guide until step 8:

```sh
$ ./bin/process.sh csvAccountExtractProcess
```
And got this error. 

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
14:27:35.118 [main] ERROR com.salesforce.dataloader.process.ProcessConfig - Error loading process: csvAccountExtractProcess configuration from config file: /home/brosyhmi/Coder97/delete_me/Scripted-Data-Loader-for-Mac-Unix/conf/process-conf.xml
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 5 in XML document from URL [file:/home/brosyhmi/Coder97/delete_me/Scripted-Data-Loader-for-Mac-Unix/conf/process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:402) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:301) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:256) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: org.xml.sax.SAXParseException: Attribute "singleton" must be declared for element type "bean".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[?:?]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:432) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[dataloader-54.0.0-uber.jar:?]
	... 19 more
14:27:35.128 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Failed to create process
com.salesforce.dataloader.exception.ProcessInitializationException: Error loading process: csvAccountExtractProcess configuration from config file: /home/brosyhmi/Coder97/delete_me/Scripted-Data-Loader-for-Mac-Unix/conf/process-conf.xml
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:98) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:301) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:256) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 5 in XML document from URL [file:/home/brosyhmi/Coder97/delete_me/Scripted-Data-Loader-for-Mac-Unix/conf/process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:402) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) ~[dataloader-54.0.0-uber.jar:?]
	... 4 more
Caused by: org.xml.sax.SAXParseException: Attribute "singleton" must be declared for element type "bean".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[?:?]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:432) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) ~[dataloader-54.0.0-uber.jar:?]
	... 4 more
```

I hope you can point me how to fix the errors.

**Comment by syahmifauzi** [comment]
I remove `singleton="false"` from `./conf/process-conf.xml` file and rerun:

```sh
$ ./bin/process.sh csvAccountExtractProcess
```

and got less errors:

```
14:56:28.850 [csvAccountExtract] ERROR com.salesforce.dataloader.security.EncryptionAesUtil - Fail to decrypt message: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
14:56:28.857 [csvAccountExtract] FATAL com.salesforce.dataloader.process.ProcessRunner - Required parameter sfdc.password is unspecified or empty
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
14:56:28.857 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process
java.lang.RuntimeException: com.salesforce.dataloader.exception.ParameterLoadException: Required parameter sfdc.password is unspecified or empty
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:181) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:262) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: com.salesforce.dataloader.exception.ParameterLoadException: Required parameter sfdc.password is unspecified or empty
	at com.salesforce.dataloader.process.ProcessRunner.validateConfigProperties(ProcessRunner.java:334) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:133) ~[dataloader-54.0.0-uber.jar:?]
	... 3 more
```
I need help with this. Thank you.

**Comment by syahmifauzi** [comment]
Okay it works, I forgot to fix `process.encryptionKeyFile=conf/myprivate.key` in `./conf/config.properties` file.

I changed `singleton="false"` to `scope="singleton"` as mentioned [here](https://github.com/mhamzas/Scripted-Data-Loader-for-Mac-Unix/issues/1#issuecomment-1022264607)

and remove `RecordTypeId=RecordTypeId` in `./conf/accountExtractMap.sdl` file because it gives `No such field recordtypeid on entity Account` error.

Anyway, thanks for the script, @mhamzas 😊

**Comment by mhamzas** [comment]
> 

Glad it worked for you!  👍
